name: debian-sapi-generator-tool
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10.13
    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        key: debian-10.13-clang16
        path: |
          ${{github.workspace}}/build/_deps

    - name: Install build tools
      run: |
        apt-get update
        env DEBIAN_FRONTEND=noninteractive \
          apt-get install -qy --no-install-recommends \
            build-essential \
            ca-certificates \
            cmake \
            file \
            git \
            gnupg \
            libc6-dev \
            lsb-release \
            make \
            software-properties-common \
            wget
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        ./llvm.sh 16 all

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: |
        mkdir -p "$GITHUB_WORKSPACE/build"
        cmake \
          -S "$GITHUB_WORKSPACE" \
          -B "$GITHUB_WORKSPACE/build" \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DSAPI_ENABLE_CLANG_TOOL=ON \
          -DSAPI_ENABLE_CLANG_TOOL_STATIC=ON

    - name: Build
      run: |
        cmake \
          --build "$GITHUB_WORKSPACE/build" \
          --config Release \
          --target sapi_generator_tool
        ( \
          cd "$GITHUB_WORKSPACE/build"; \
          mv sandboxed_api/tools/clang_generator/sapi_generator_tool \
            sapi_generator_tool-linux-x86_64; \
        )

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: sapi_generator_tool-linux
        path: ${{github.workspace}}/build/sapi_generator_tool-linux-x86_64
